# Generated by Django 4.2.23 on 2025-07-14 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSchedule",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the task to execute", max_length=255
                    ),
                ),
                (
                    "task_args",
                    models.JSONField(
                        default=list, help_text="Positional arguments for the task"
                    ),
                ),
                (
                    "task_kwargs",
                    models.JSONField(
                        default=dict, help_text="Keyword arguments for the task"
                    ),
                ),
                (
                    "callback_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to POST to when task execution is triggered",
                        null=True,
                    ),
                ),
                (
                    "schedule_time",
                    models.DateTimeField(
                        blank=True, help_text="When to execute the task", null=True
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=300, help_text="Task timeout in seconds"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts remaining"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Task execution result or error",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orkera_task_schedule",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="orkera_ta_user_id_9af7d5_idx"
                    ),
                    models.Index(
                        fields=["status", "schedule_time"],
                        name="orkera_ta_status_ef76fb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="orkera_ta_created_59f4de_idx"
                    ),
                ],
            },
        ),
    ]
