# Generated by Django 4.2.23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='timeout',
        ),
    ]
