# Generated by Django 4.2.23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_timeout_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='retry_count',
        ),
    ]
