# Generated by Django 4.2.24 on 2025-09-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_remove_retry_count_field"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="taskschedule",
            new_name="orkera_task_user_id_b85c8c_idx",
            old_name="orkera_ta_user_id_9af7d5_idx",
        ),
        migrations.RenameIndex(
            model_name="taskschedule",
            new_name="orkera_task_status_32466f_idx",
            old_name="orkera_ta_status_ef76fb_idx",
        ),
        migrations.RenameIndex(
            model_name="taskschedule",
            new_name="orkera_task_created_4ee4ce_idx",
            old_name="orkera_ta_created_59f4de_idx",
        ),
    ]
