# Generated by Django 4.2.24 on 2025-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0004_rename_orkera_ta_user_id_9af7d5_idx_orkera_task_user_id_b85c8c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskschedule",
            name="callback_url",
            field=models.URLField(
                help_text="URL to POST to when task execution is triggered"
            ),
        ),
    ]
