# Generated by Django 4.2.28 on 2026-02-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_taskschedule_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='cron_expression',
            field=models.CharField(blank=True, default='', help_text="Cron expression, e.g. '*/5 * * * *' (minute hour day month weekday)", max_length=100),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Stop recurring execution after this time', null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='interval_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Repeat every N seconds (interval schedule)', null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Pause recurring task without deleting it'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Last time this task was dispatched', null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='max_retries',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of retry attempts (0 = no retries)'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Next calculated execution time (UTC). Managed by the system.', null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Current retry attempt number'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='retry_delay_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Base delay between retries in seconds'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='retry_policy',
            field=models.CharField(choices=[('none', 'No retries'), ('fixed', 'Fixed delay'), ('exponential', 'Exponential backoff'), ('linear', 'Linear backoff')], default='none', help_text='Retry strategy on callback failure', max_length=20),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='run_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this task has been dispatched'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='schedule_type',
            field=models.CharField(choices=[('one_off', 'One-off'), ('cron', 'Cron'), ('interval', 'Interval')], default='one_off', help_text='Type of schedule: one-off, cron, or interval', max_length=20),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='task_timezone',
            field=models.CharField(default='UTC', help_text="IANA timezone for schedule interpretation, e.g. 'America/New_York'", max_length=63),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='schedule_time',
            field=models.DateTimeField(blank=True, help_text='When to execute (one-off) or first execution (recurring)', null=True),
        ),
        migrations.AddIndex(
            model_name='taskschedule',
            index=models.Index(fields=['next_run_at', 'status'], name='orkera_task_next_ru_c69d6e_idx'),
        ),
    ]
