# Generated by Django 4.2.28 on 2026-02-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_taskschedule_cron_expression_taskschedule_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('execution_number', models.PositiveIntegerField(help_text='Sequential execution number for this task (1, 2, 3, ...)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('http_response_body', models.TextField(blank=True, max_length=10000, null=True)),
                ('http_response_headers', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_traceback', models.TextField(blank=True, max_length=20000, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_retry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.taskschedule')),
            ],
            options={
                'db_table': 'orkera_task_execution',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task', '-started_at'], name='orkera_task_task_id_c4a065_idx'), models.Index(fields=['status', '-started_at'], name='orkera_task_status_899550_idx'), models.Index(fields=['started_at'], name='orkera_task_started_d5b2f8_idx')],
                'unique_together': {('task', 'execution_number')},
            },
        ),
    ]
