# Generated by Django 4.2.28 on 2026-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_taskexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL to POST to when task execution is triggered', null=True),
        ),
    ]
