# Generated by Django 4.2.28 on 2026-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_taskschedule_webhook_secret'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskschedule',
            name='orkera_task_status_32466f_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskschedule',
            name='orkera_task_created_4ee4ce_idx',
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='cron_expression',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='max_retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='next_run_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='retry_delay_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='retry_policy',
            field=models.CharField(choices=[('none', 'No retries'), ('fixed', 'Fixed delay'), ('exponential', 'Exponential backoff'), ('linear', 'Linear backoff')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='run_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='schedule_type',
            field=models.CharField(choices=[('one_off', 'One-off'), ('cron', 'Cron'), ('interval', 'Interval')], default='one_off', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task_args',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task_kwargs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task_timezone',
            field=models.CharField(default='UTC', max_length=63),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
